export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY';
export const GET_ONE_CATEGORY_START = 'GET_ONE_CATEGORY_START';
export const GET_ONE_CATEGORY_FAIL = 'GET_ONE_CATEGORY_FAIL';
