export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const GET_ONE_POST = 'GET_ONE_POST';
export const GET_ONE_POST_START = 'GET_ONE_POST_START';
export const GET_ONE_POST_FAIL = 'GET_ONE_POST_FAIL';

export const SEARCH_POST = 'SEARCH_POST';
export const SEARCH_POST_START = 'SEARCH_POST_START';
export const SEARCH_POST_FAIL = 'SEARCH_POST_FAIL';
